from . import sale_order
from . import sale_order_line
from . import res_partner
from . import product_template
from . import alfinf_trace
from . import alfinf_family
from . import alfinf_finca
from . import alfinf_variedad
from . import alfinf_recinto
